version: '3'

services:
  frontend:
    build: ./frontend
      environment:
    - NODE_VERSION=18.19.1
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3001:3001"